### ISSUE TITLE
Make the youtube browser time sensitive

### ISSUE THREAD

**Issue by ehsteve** [Helioviewer-Project/helioviewer.org#103]
It would be great if the youtube browser showed movies that were created near the time that you are currently browsing.

**Comment by wafels** [comment]
We've had some thoughts in the past about how to browse through the youtube movies better, but this idea is quite a simple one.  Make the youtube browser sensitive to the Observation Time...

**Comment by wafels** [comment]
I think this should be targeted to 3.1 since this may require some re-design of the existing YouTube browse UI, and it changes the function of the YouTube browser substantially.  For example, you might want to browse earlier times in the viewport, but still keep the most recent movies available.  Also, when  browsing earlier times, we need some indication of the time range of the movie,  along with the type of image data used.  This could be implemented via the same tooltip which pops up when you browse your own list of movies.  Also, we will need to decide what list of movies to show.  The first choice would be movies that span the requested observation time.  For example, if the requested observation time is 2012-06-09 12:34:56, then we should search for movies that contain that time.  There is some thought required about how to order these movies, and movies that do not span the requested time range.

**Comment by wafels** [comment]
Should also be able to scroll much further back in time.  The last 20 videos is not enough!

**Comment by wafels** [comment]
So when I set the observation time, does the time-sensitive YouTube browser show me all the movies that contain the given observation time?

**Comment by ddialer** [comment]
YouTube browser show only 20 movies from that time. Also Added "SHOW MORE" button at the end of the list to load more videos

**Comment by ddialer** [comment]
Compleated and released in v3.1
