### ISSUE TITLE
Filaments do not appear in viewer window

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#162]
There should be a number of filament pins in the viewer window, but there are none.

![screen shot 2016-09-12 at 11 17 14 am](https://cloud.githubusercontent.com/assets/983575/18441317/a14b913c-78da-11e6-9e9d-435b155ba12a.png)

**Comment by ddialer** [comment]
It is related to the "Representation of zero-duration events #155" bug. Because zero seconds events are so small, I have to stretch them on the timeline manually. This is why this is overlap sometimes observation date. 

But, I lowered stretching function so events bars will be smaller now. And I  disable highlight on zero seconds events if the event bar only overlaps observation date

**Comment by wafels** [comment]
Using this solution with zero duration events requires some changes to the pop-up window and what happens when the user clicks on them.  Firstly, the pop-up window must report that the start and end time are the same.  At the moment, the start and end time depend on the timeline window duration.  Secondly, when the user double clicks on a zero duration event, then the observation time and date must go to the time of the zero duration event, and not at the time corresponding to where the mouse is.  This is because the zero duration event is at exactly one time; failure to reset observation time and date mean that the features are not visible in the viewer window.

**Comment by ddialer** [comment]
All the times and events for zero duration event is corrected.

**Comment by wafels** [comment]
fixed
