### ISSUE TITLE
Movies and screenshots do not respect layering order on screen.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#257]
The LASCO C2/C3 layering order in the viewport is not respected in movies and screenshots.  This is a screengrab:
<img width="1268" alt="Screen Shot 2019-03-16 at 5 02 02 PM" src="https://user-images.githubusercontent.com/983575/54481630-79fe6280-480d-11e9-8ff4-f932c04ae155.png">

and this is the download generated by helioviewer.org

![2019_03_09_19_45_29_LASCO_C3__LASCO_C2](https://user-images.githubusercontent.com/983575/54481634-913d5000-480d-11e9-8a97-2433d67be877.png)

**Comment by wafels** [comment]
The layering in the viewport should be respected in the movies/screenshots.

**Comment by Helioviewer-Kirill** [comment]
After some digging, this is not a bug and is by design in the codebase.
Layering order is set based on a pre-defined list of instruments.

As it stands, the api will always render SOHO LASCO C3 over SOHO LASCO C2 
and STEREO_A/B SECCHI COR2 over STEREO_A/B SECCHI COR1.

My assumption is that this preset layering order was implemented to create a properly layered image. 
However, it does not respect the layering order, on screen, as seen in the front-end. 

This can be disabled. Let me know how I should proceed.

**Comment by wafels** [comment]
I think the layering order on screen should be respected.  It's easier to understand how helioviewer works that way.

**Comment by Helioviewer-Kirill** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed
