### ISSUE TITLE
''u-psud.fr wants to access your Google Account'' IT IS SAFE TO UPLOAD FROM " .u-psud.fr/. " ?

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#270]
Hi, after https://helioviewer.org/ is down for maintenance, and i try to upload from https://helioviewer.ias.u-psud.fr/, it says this: 
![Untithhjhjled](https://user-images.githubusercontent.com/20747347/68906710-e55a5480-074d-11ea-9aa0-c3b7a76084af.png)
**IT IS SAFE TO UPLOAD FROM .u-psud.fr/.?**

image from https://helioviewer.org/ with maintenance note:
![Untitjhjhjled](https://user-images.githubusercontent.com/20747347/68906770-18044d00-074e-11ea-915c-249cdab060a1.png)

Thanks

**Comment by bogdanni** [comment]
You can trust https://helioviewer.ias.u-psud.fr/, it is a mirror Helioviewer site.

**Comment by Anthrwpos** [comment]
ok, but google says this when i choose my account:
![Unthjhjhjhitled](https://user-images.githubusercontent.com/20747347/68973874-ffe90800-07f7-11ea-9762-1d2c8f31907c.png)

**Comment by dgarciabriseno** [comment]
I looked into this recently. The problem here at least on https://helioviewer.org's side is that there are certain obligations Google is requesting in order to allow continued access to the API for public use. It will be some time before be can resolve this. For now users will have to download the video and upload it to Youtube manually.

**Comment by dgarciabriseno** [comment]
See https://github.com/Helioviewer-Project/helioviewer.org/issues/292#issuecomment-1424650429
