### ISSUE TITLE
cursor measurement feature has disappeared

### ISSUE THREAD

**Issue by ginnymc** [Helioviewer-Project/helioviewer.org#279]
The ability to measure positions with the cursor has disappeared.  This was a useful feature, and I hope it will return!

**Comment by wafels** [comment]
Thanks for using helioviewer.org!

We have temporarily disabled the cursor's ability to report its position on the Sun.  This is because the position being calculated is not as accurate as we would like it to be.  Therefore, to ensure that our users are not being given incorrect information, we disabled this feature.

We intend to bring this feature back as soon as we have implemented more accurate positional calculations.

**Comment by ginnymc** [comment]
That is a shame since I have incorporated the Helioviewer into my Intro Astronomy Lab course.  Is it possible to bring it back with a cautionary message, perhaps?

Thanks,
Ginny McSwain


----
M. Virginia McSwain
Associate Professor of Physics
Lehigh University

**Comment by wafels** [comment]
We did have a cautionary message, but I know that some people were ignoring it.  We plan on bringing back the co-ordinates, along with the ability to transform to other coordinate systems.
