### ISSUE TITLE
Low  definition

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#285]
I noticed that movies I post on youtube from your site is now in low definition why is that? I also always give full credit to Helioviewer.org for images and videos made from this site. 

Thanks in advance for your reply.
👍

**Comment by wireeye** [comment]
Need to remove the HD settings if you can't fix this issue it is misleading. I wrote in Jun and this problem still hasn't been fixed.

**Comment by Helioviewer-Kirill** [comment]
Hello,

Thanks for bringing this issue to our attention.  In order to help, we would like to ask you for some additional information so we can fully understand the issue.

1. Could provide links to the video and screenshots of the setting you used when creating the video?
2. Are you using the "Full Viewport" or "Select area" option?
3. What is your screen resolution?
4. What images are you making movies of?

This will help us understand what you are seeing.  Also, images from different instruments can have a different number of pixels.  This is because different instruments have different capabilities, and some instruments have lower number of pixels compared to others. For example, SDO AIA images are typically 4096 x 4096 pixels, whereas SOHO LASCO images are typically 1024 x 1024 pixels.

The "HD" settings simply upscale the selected viewport to match the target resolution.  So an HD movie will be created, but the amount of detail that is available depends on the size of selected area and the resolution of the data.  For example, it is possible to select a single LASCO pixel and export that to an HD movie.  Helioviewer will upscale that single pixel to an HD movie.  What will be seen is still what was in that original single pixel - it's just been upscaled to a HD movie (there may also be some some artifacts from the stretching used to up-scale that single pixel to an HD movie).

We suggest that you use the "Original" setting as this provides the sharpest video and does not apply any stretching artifacts from up-scaling the video. Using your browser's full screen mode and selecting "Full Viewport" will also capture as many pixels as you have available which will result in a higher base resolution of the video.

**Comment by wireeye** [comment]
![Screenshot_2020-08-21 Helioviewer org(2)](https://user-images.githubusercontent.com/35879228/90928495-f8790f80-e3c4-11ea-83c2-a176baed5ffa.png)
Thanks for reply. While making videos using  SDO AIA  set to  "Original" setting when viewed on youtube or bitchute it has real low definition I am suing a flate screen tv for my computer monitor set at 1360x768 
![Screenshot_2020-08-21 Helioviewer org(1)](https://user-images.githubusercontent.com/35879228/90928328-ad5efc80-e3c4-11ea-89c3-ffc7e8fa9709.png)
![Screenshot_2020-08-21 Helioviewer org](https://user-images.githubusercontent.com/35879228/90928331-adf79300-e3c4-11ea-9901-cb9b8986ac28.png)

**Comment by Helioviewer-Kirill** [comment]
Thanks for these screenshots. 

Can you post a link to the YouTube video after you upload it?
Are you using the "Full Viewport" or "Select area" option?

**Comment by wireeye** [comment]
Here is a screen shot. SDO 171
![Screenshot_2020-08-21 Active region of the sun AIA 171 (2020-05-21 05 15 21 - 2020-05-25 15 21 21 UTC) - YouTube](https://user-images.githubusercontent.com/35879228/90934375-2f542300-e3cf-11ea-8069-261d471a5ffe.png)

**Comment by wireeye** [comment]
Greetings to you, I still wish to inquire  as to why the 720p HD still isn't working on the helioviewer website. It doesn't work on the SDO, SOHO or the stereo-A, On the SOHO LASCO C2 I thought about trying the 720p since it had been so long ago since I wrote about the problem, but even using full screen it said "sorry we were unable to create the movie you requested" blah, blah. Have you tried to create a movie on helioviewer using the 720p HD or higher? That may be the best way to see for yourself what I am talking about. Truly, thanks for your time and consideration.
![Screenshot_2021-01-28 Helioviewer org](https://user-images.githubusercontent.com/35879228/106213213-28a9b300-619a-11eb-9eb1-239443ef58e7.png)

**Comment by dgarciabriseno** [comment]
@wireeye Kirill isn't working on this project anymore so we may have to rehash some of this out. The point he was trying to make is that way videos are created is that it takes the view you're looking at and stretches it to fit the resolution you request. This can result in "low quality" if you're using a 1360x768 view and you create a 1920x1080 video. since it will just be that 1360x768 video stretched to 1920x1080.

> I still wish to inquire as to why the 720p HD still isn't working on the helioviewer website.

This will be updated on Helioviewer.org next month. The patch has been applied to https://beta.helioviewer.org/ You can help us test it by making 720p movies there.

**Comment by dgarciabriseno** [comment]
this has been merged.
