### ISSUE TITLE
LASCO C2 and C3 are a day behind

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#316]
Greetings, First I would like to say, I am glad Helioviewer is back up and running. The problem I have is that your LASCO C2 and C3 are a day behind when trying to make a movie, are you aware of this problem and if so are you working on fixing this? Thanks for your time, have a good day.  🤗

**Comment by wafels** [comment]
Thank you for pointing this out. I think I have located the source of the problem. The problem was that the script that checks for new data on a regular and frequent (many times a day) basis was not running.  However, there is another script that runs once a day that attempts to fill in any gaps over the previous week. That script was picking up the data that had accumulated over the day, but only once a day. Therefore new data was only appearing on a daily basis. I am fairly sure the same situation also applied to images from STEREO and PROBA2 (note that data is downlinked from those missions at a different frequency compared to LASCO).

I have restarted the relevant scripts. Images from LASCO from today (2021-10-18) is now available on helioviewer.org). I will leave this issue open for today; I will check again over the next couple of days to make sure recent data is appearing.

Finally, I apologize for the interruption to helioviewer.org services this year.
