### ISSUE TITLE
HEK updating correctly?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#317]
Are the features and events from the HEK updating correctly? I am not sure. This should be checked.

**Comment by wireeye** [comment]
Thanks for asking, stereo-A co1 and cor2 is three days behind, don't know if you can fix this problem, SDO, and SOHO seem to be spot on, If Helioviewer is on UTC time it should be four hours a head of me in my time zone, But video ends  three hours a head, so that is pretty close. Thanks for taking the time to reach out.

**Comment by dgarciabriseno** [comment]
It looks like we collect HEK data on helioviewer.org every 30 minutes, can you clarify what you mean by "updating correctly"?

**Comment by wafels** [comment]
@wireeye - The issue for STEREO-A COR1 and COR2 is outside the control of Helioviewer. STEREO downloads science-quality data at a very low cadence, so a three day delay is not unusual. This is part of nominal mission operations. SDO downloads data constantly, and so it is common for SDO images to have a relatively short delay compared to real time. SOHO has several downloads a day and so it is common for SOHO images to have delays on the order of minutes to hours compared to real time.

**Comment by wafels** [comment]
The features and events from the HEK seem to be updating correctly (as of the time of this comment). Closing this issue.
