### ISSUE TITLE
Issue with interactive tutorial

### ISSUE THREAD

**Issue by AdnanBean** [Helioviewer-Project/helioviewer.org#318]
The fifth part of the interactive tutorial does not load. The screen becomes darkened, but then nothing happens.

**Comment by wafels** [comment]
I was not able to reproduce this error. Can you give some details on the browser you were using? Does the error still occur?

**Comment by dgarciabriseno** [comment]
I was able to reproduce. It's tricky.
![image](https://user-images.githubusercontent.com/94071409/149011423-331e637d-82ae-4d76-b03c-56969989418d.png)
It is displaying the tutorial next to the celestial bodies dropdown on the sidebar.
If your celestial bodies label is far down on the screen because you have multiple layers or the HEK events open, then the display will be off screen. Like this:
![image](https://user-images.githubusercontent.com/94071409/149011879-fb667909-09a1-4010-859d-64f2a730e18a.png)
And if i added more layers, the tutorial box would be below the viewport, and scrolling is disabled with the overlay so it's essentially frozen at that point.

**Comment by btaylor-sesda** [comment]
I'm working on a fix to this that'll hide the components when the Celestial Bodies part of the tutorial shows. I've added an update to Tutorial.js in HVBeta to accommodate this. Testing.
