### ISSUE TITLE
Video flow is like frame by frame from AIA

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#319]
Hi, as the title says, the video it's missing some frames from AIA filters, why this happening? Or is just me? Thanks

**Comment by Anthrwpos** [comment]
Hi, any update about the above issue? In SDO all the filters have missing parts in videos. Why? Thanks

**Comment by dgarciabriseno** [comment]
Hi @Anthrwpos can you send me an example video to look at?

**Comment by Anthrwpos** [comment]
Hi, you can see a lot of videos in [helioviewer](https://helioviewer.org/) from users. Only from SDO>AIA videos. I don't know why this is happening

**Comment by dgarciabriseno** [comment]
I see, they are choppy. It looks like right now how we're getting data is leaving some gaps. I'll work on patching this. Thanks for pointing this out.

**Comment by Anthrwpos** [comment]
But in this [helioviewer](https://helioviewer.ias.u-psud.fr/#) ( .fr ), the flow it's good.

**Comment by dgarciabriseno** [comment]
I updated the downloader on helioviewer.org to make sure there aren't 30 min to hour long gaps for AIA data. Newer movies (newer than 2022-01-11 16:00:00 UTC) shouldn't skip so much.
Let's keep an eye on it over the next week to see if the patch works.

**Comment by Anthrwpos** [comment]
Ok, thanks. But why it make skips?

**Comment by dgarciabriseno** [comment]
The videos are made by putting the images we have available into a movie format. Since the server had large gaps in AIA data, it looks like it's skipping.

Take this video for example: https://helioviewer.org/?movieId=JcpN5 
The timestamp shows the image being displayed is 11:47:10, then the very next frame is 12:37:58. The server doesn't have any AIA 211 images between 11:47:10 and 12:37:58.
So when you play the video it is actually skipping 50 minutes forward.

![image](https://user-images.githubusercontent.com/94071409/149146517-4bc3269d-caf8-44c4-9ca3-1c8d71d983af.png)
![image](https://user-images.githubusercontent.com/94071409/149146684-d9915039-17a7-43a0-8184-c02a2f70927a.png)

**Comment by Anthrwpos** [comment]
But in [this](https://helioviewer.ias.u-psud.fr/) website, the video is smooth. Why? What's the difference?

**Comment by Anthrwpos** [comment]
And why from [this](https://helioviewer.ias.u-psud.fr/) site i can post video, but it's private (locked) only?

**Comment by dgarciabriseno** [comment]
Sorry, was out for a while. The difference is they're independently operated servers. On our side we made a patch since we were running low on disk space, this will be resolved soon.

You can't upload to YouTube on helioviewer.org since there's some legal business that we haven't worked through with the YouTube API. I think the IAS version has the same problem. For now you'll have to work around it by downloading the video with the link and uploading manually to YouTube.

**Comment by dgarciabriseno** [comment]
Video flow should be smooth on helioviewer.org now, at least for dates > 01/12/2022, so I am marking this as closed.

**Comment by Anthrwpos** [comment]
Hi, again [flow](https://helioviewer.org/?movieId=JV2N5) is with gap.
