### ISSUE TITLE
helioviewer.org starts up with the same date all the time

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#345]
A user has reported that on launching helioviewer.org it always goes to the same date 2022/03/03 05:00. The correct behavior should be to go to the current UT time on launch.

**Comment by btaylor-sesda** [comment]
@wafels It looks like the problem is that the PSP encounter updates are triggered even when neither SOHO or Stereo-A's PSP selection is made. So it needs a conditional to check whether or not PSP is selected onload - and then if checked, it should run the encounter piece. I added the fix to develop.helioviewer and beta.helioviewer but I'm still working on it.

**Comment by dgarciabriseno** [comment]
@btaylor-sesda let me know when the patch is ready and I'll merge it in

**Comment by btaylor-sesda** [comment]
@wafels @dgarciabriseno the fix should be in place now. Let me know if it's not working properly. The only file updated was resources/js/CustomHandling/CustomHandling.js

**Comment by dgarciabriseno** [comment]
Updated the server with the change.
