### ISSUE TITLE
Feature and event pop-ups don't pop up on mobile

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#359]
Features and events are shown on mobile on screen, but you can't click on them and get any more information. It would be good if the pop-ups that appear on the desktop version also appear on the mobile version.

**Comment by btaylor-sesda** [comment]
@wafels Currently the way the Helioviewer was designed, the features/events aren't clickable even when using the desktop design on mobile. I'll have to investigate the cause of this.

**Comment by btaylor-sesda** [comment]
@dgarciabriseno on dev, the toptouchlayer <div> you're using for the new zooming, is z-Index layered over those marker elements. So it looks to be blocking them from being accessed. 

Perhaps setting a conditional so that the div is only layered on top when 2 fingers are touching the screen, would help. At least that's similar to what I was doing prior to your current zoom updates.
