### ISSUE TITLE
"loading data" at the top of the page, when i click "newest" until refresh the page

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#407]
Hi, i noticed that when i click "newest", at the top of the page the "loading data" phrase is there until i reload the page, and before the refrash, i cannot use the top part of the page. Why? Thanks

**Comment by dgarciabriseno** [comment]
Which observatory are you using?

**Comment by dgarciabriseno** [comment]
@Anthrwpos ?

If it was Hinode XRT it's because the dataset for XRT is pretty complicated so the searches take a long time. It used to take like 12 minutes and I thought I fixed that, but I tested it again after seeing this issue and it was taking around 12 seconds.

I have another patch that I'm going to push here in a minute that brings that back down to ~1 second, so it shouldn't appear to get stuck anymore.

If it's not Hinode XRT or if it's still taking minutes, then I'll still need more info to answer why.

**Comment by Anthrwpos** [comment]
It's at every observatory I checked.
I've noticed this in the past few days.

It's only me? Or is general?

**Comment by dgarciabriseno** [comment]
I haven't seen it or gotten any other reports of it. It sounds like it's probably problem in the front end scripts.

Maybe you can get me the console log?
- Go to https://helioviewer.org?debug=True
- Right click > inspect element
- In the window that comes up there's a tab named "Console" click that
- Once you have that open, click newest so that the loading spinner gets stuck
- If anything red comes up on the console it will have a little red arrow next to it, click the red arrow to expand it then paste the contents from the console here.

**Comment by dgarciabriseno** [comment]
@Anthrwpos is this still happening?

**Comment by Anthrwpos** [comment]
> @Anthrwpos is this still happening?

In the last three days I've been using it a little more sparingly, so I'll update soon, because I haven't noticed. Thanks

**Comment by Anthrwpos** [comment]
> @Anthrwpos is this still happening?

I think the last days, it doesn't have this loading issue.

**Comment by Anthrwpos** [comment]
Hi, again "loading data" happening. And i can't select any icon from the bar where the name ''helioviewer'' is and all the right side icons.

**Comment by Anthrwpos** [comment]
''Loading data'', now even with refreshing the page, is still loading. Why?
![Untitled](https://user-images.githubusercontent.com/20747347/231683765-3d2ff75f-e596-4c87-b7ce-5fbc3aef99b6.png)

**Comment by dgarciabriseno** [comment]
Looking into this now.
