### ISSUE TITLE
Figure out why we're getting flagged for low contrast

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org#416]
There are low contrast errors on the mobile menu, I think it's intentional because the mobile menu isn't displayed on desktop, but if that's the case then it shouldn't get flagged.

See "Contrast Errors" here https://wave.webaim.org/report#/helioviewer.org

**Comment by btaylor-sesda** [comment]
@wafels The contrast errors in WAVE indeed look to be due to hidden elements from Mobile and the calendar being detected by the tool.

The Mobile stylesheet is only applied to those Mobile-based elements if the code detects that the user is being served the page on a mobile browser. So those particular callouts can be disregarded.

According to WAVE's Help page:
_If WAVE has detected an error in an element that is hidden and that is never presented to the end user, or that is perhaps modified to address the error before being presented (something WAVE cannot detect), the WAVE error can be ignored_
