### ISSUE TITLE
Mouse coordinates not working in any browser

### ISSUE THREAD

**Issue by eimason** [Helioviewer-Project/helioviewer.org#477]
Hello, the mouse coordinates aren't functioning at all anymore (at least for Macs), regardless of the browser. All of the other keyboard shortcuts I tried work, but the `m` does not. It would be really great if this was reintroduced at some point. Thank you!

**Comment by dgarciabriseno** [comment]
Hi @eimason, thanks for bringing this to my attention. This feature was disabled on Helioviewer due to concerns about the mouse coordinate's accuracy.

It's temporarily enabled on https://beta.helioviewer.org while we re-evaluate its accuracy and update the UI to reflect some information users should know about it.

What's important to note when using these coordinates is that helioviewer normalizes the scale of images so that everything can assume a sun-earth distance of 1-AU for the arcsecond coordinates. This may lead to different coordinates for the same position when using other applications.

Also when looking at coordinates for features & events, the event has a single position for for a window of time. Helioviewer accounts for the solar rotation over that window of time so the coordinate of an event at a specific observation time may be different than the coordinate provided by the source data.

**Comment by dgarciabriseno** [comment]
This was completed in September 2023.
