### ISSUE TITLE
Movie player requires Flash

### ISSUE THREAD

**Issue by ehsteve** [Helioviewer-Project/helioviewer.org#95]
Recommendation is to move to an html5 video player. Who uses flash anymore?!

**Comment by ddialer** [comment]
I updated media player with http://mediaelementjs.com/. This is open source project and all source  code available at https://github.com/johndyer/mediaelement/

The reason I choose MediaElementJS is because player have fallbacks for Flash and Silverlight and will always choose best available movie format for specific web browser

**Comment by ddialer** [comment]
API commit: https://github.com/Helioviewer-Project/api/commit/a8558714300e09a4fc652c76aa89e010822038b6

**Comment by wafels** [comment]
Does this mean that we only need to make the movie in one format from now on?

**Comment by ddialer** [comment]
Yes, but for the best support we should keep at least HQ mp4 and Webm files (https://www.webtvsolutions.com/support.php?s=other_docs&d=flv_vs_h264_vs_webm). 

And we can safely remove flash video and regular quality mp4 video.

**Comment by wafels** [comment]
New player has been installed.

**Comment by wafels** [comment]
fixed.
